[package]
name = "u50_style"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
fs-err = { workspace = true }
indicatif = { workspace = true }
leptos = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
similar = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uv-cache = { workspace = true }
uv-cache-info = { workspace = true }
uv-client = { workspace = true }
uv-distribution-filename = { workspace = true }
uv-distribution-types = { workspace = true }
uv-extract = { workspace = true }
uv-installer = { workspace = true }
uv-pep508 = { workspace = true }
uv-preview = { workspace = true }
uv-pypi-types = { workspace = true }
uv-python = { workspace = true }
uv-redacted = { workspace = true }
uv-virtualenv = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
