//! The console (text-mode) renderer: style50 3.0.0 parity output.

use std::io::Write;
use std::path::Path;

use crate::language::{comment_hint, detect_language};
use crate::rendering::character::render_character;
use crate::rendering::palette::{bold, bright_white, cyan, green, reset, yellow};
use crate::rendering::split::render_split;
use crate::rendering::unified::render_unified;
use crate::request::{FileResult, Output, Request};

use super::HEADER_RULE;
use super::Renderer;

/// Writes the style50 3.0.0-parity per-file console output and
/// `error: <path>: <message>` lines to stderr. JSON-mode requests are
/// served by [`JsonRenderer`] instead; if a JSON output is requested of
/// this renderer directly, it falls back to the unified diff.
///
/// Character mode reproduces the original's `to_ansi` presentation: a
/// bold-bright-white `Results generated by u50 v<version>` banner (once,
/// u50 branding — a documented divergence), a cyan `::::::::::::::`
/// header per file when the run covers more than one file, green
/// `Looks good!` for clean files (followed by the yellow `But consider
/// adding more comments!` hint when the comment ratio is under 0.10),
/// and the char-diff block (with legend and the yellow `And consider
/// adding more comments!` hint) from [`render_character`] for dirty
/// ones. Split/unified stay plain
/// per-dirty-file diffs (clean files print nothing) — a by-design
/// divergence: the original routes every text mode through `to_ansi`
/// (banner, cyan headers, green `Looks good!`) and colors its
/// split/unified lines; see `STYLE50_V3_CROSSCHECK.md` registers #6/#7.
pub struct ConsoleRenderer {
    pub(crate) output: Output,
    pub(crate) color: bool,
    pub(crate) out: Box<dyn Write>,
    pub(crate) banner_emitted: bool,
    pub(crate) total_files: usize,
}

impl Renderer for ConsoleRenderer {
    fn begin(&mut self, _req: &Request) {
        if matches!(self.output, Output::Character) && !self.banner_emitted {
            self.banner_emitted = true;
            let banner = format!("Results generated by u50 v{}", env!("CARGO_PKG_VERSION"));
            let _ = if self.color {
                writeln!(self.out, "{}{banner}{}", bold(), bright_white())
            } else {
                writeln!(self.out, "{banner}")
            };
        }
    }

    fn total_files(&mut self, count: usize) {
        self.total_files = count;
    }

    fn skipped(&mut self, path: &Path) {
        eprintln!("unknown file type \"{}\", skipping...", path.display());
    }

    fn file(&mut self, result: &FileResult) {
        if matches!(self.output, Output::Character) {
            // style50 prints the cyan header for every file's block —
            // clean and dirty — but only when a run covers more than one
            // file. Errored files keep their bare stderr line (u50's
            // documented error-channel divergence) and get no header.
            if self.total_files > 1 {
                let name = result.path.display().to_string();
                let _ = if self.color {
                    writeln!(
                        self.out,
                        "{}{HEADER_RULE}\n{name}\n{HEADER_RULE}{}",
                        cyan(),
                        reset()
                    )
                } else {
                    writeln!(self.out, "{HEADER_RULE}\n{name}\n{HEADER_RULE}")
                };
            }
            if result.clean {
                let _ = if self.color {
                    writeln!(self.out, "{}Looks good!{}", green(), reset())
                } else {
                    writeln!(self.out, "Looks good!")
                };
                // style50's `to_ansi` clean path: after `Looks good!`, a
                // yellow `But consider...` line when the comment hint
                // fires (no trailing blank).
                if self.file_hints(result) {
                    let _ = if self.color {
                        writeln!(
                            self.out,
                            "{}But consider adding more comments!{}",
                            yellow(),
                            reset()
                        )
                    } else {
                        writeln!(self.out, "But consider adding more comments!")
                    };
                }
                return;
            }
        } else if result.clean {
            return;
        }
        let (Some(source), Some(formatted)) = (&result.source, &result.formatted) else {
            return;
        };
        let hint = self.file_hints(result);
        let rendered = match self.output {
            Output::Character => render_character(source, formatted, self.color, hint),
            Output::Split => render_split(source, formatted, self.color),
            // `Json`/`Score`/`Html` never reach this renderer through
            // [`builtin_renderer`]; direct use falls back to the unified
            // diff, like JSON always has.
            Output::Unified | Output::Json | Output::Score | Output::Html => {
                render_unified(source, formatted, &result.path)
            }
        };
        let _ = write!(self.out, "{rendered}");
    }

    fn file_error(&mut self, path: &Path, message: &str) {
        eprintln!("error: {}: {message}", path.display());
    }
}

impl ConsoleRenderer {
    /// Whether style50's comments hint fires for `result`'s normalized
    /// original (character mode only — the original computes the hint in
    /// `to_ansi`): `file["comments"]`, i.e. the comment ratio is strictly
    /// under 0.10. HTML/CSS/SQL are never hinted (no `count_comments`).
    fn file_hints(&self, result: &FileResult) -> bool {
        matches!(self.output, Output::Character)
            && result
                .source
                .as_deref()
                .zip(detect_language(&result.path))
                .is_some_and(|(source, language)| comment_hint(source, language))
    }
}
