//! Pluggable output rendering for style checks: a [`Renderer`] receives
//! the results of a run as a stream of events, and built-in implementations
//! reproduce the legacy console and JSON output byte for byte.
//!
//! Rendering is decoupled from processing ([`crate::engine::run_with`]):
//! [`crate::engine::run_with_renderer`] drives any [`Renderer`] over a
//! report, so custom sinks (HTML, SARIF, an editor panel, ...) need only
//! implement the trait — no changes to the engine.

use std::io::Write;
use std::path::Path;

use serde::Serialize;
use similar::ChangeTag;

use crate::language::{comment_hint, detect_language, style50_count_lines};
use crate::render::{
    BOLD, BRIGHT_WHITE, CYAN, GREEN, RESET, YELLOW, json_document, line_diff, render_character,
    render_split, render_unified,
};
use crate::request::{FileResult, Output, Report, Request};

/// The 14-colon rule of style50's per-file header ("Use same header as
/// more.").
pub(crate) const HEADER_RULE: &str = "::::::::::::::";

/// A sink for the events of a style check.
///
/// Event order: [`begin`](Renderer::begin), then one
/// [`skipped`](Renderer::skipped) per unsupported regular file found while
/// walking a directory operand, then one [`file`](Renderer::file) per
/// successfully processed file and one [`file_error`](Renderer::file_error)
/// per file that could not be processed, then [`finish`](Renderer::finish).
/// Every method has an empty default, so a custom renderer only overrides
/// what it needs.
///
/// # Examples
///
/// A minimal HTML renderer: a table row per file, wrapped in a document at
/// the end.
///
/// ```
/// use u50_style::{FileResult, Output, Renderer, Report, Request};
///
/// struct HtmlRenderer {
///     buf: String,
/// }
///
/// impl Renderer for HtmlRenderer {
///     fn begin(&mut self, _req: &Request) {
///         self.buf.push_str("<html><body><table>\n");
///     }
///
///     fn file(&mut self, result: &FileResult) {
///         self.buf.push_str(&format!(
///             "<tr><td>{}</td><td>{}</td></tr>\n",
///             result.path.display(),
///             result.clean
///         ));
///     }
///
///     fn finish(&mut self, _report: &Report) {
///         self.buf.push_str("</table></body></html>\n");
///     }
/// }
///
/// let req = Request {
///     files: vec![],
///     output: Output::Character,
///     color: false,
/// };
/// let mut renderer = HtmlRenderer { buf: String::new() };
/// renderer.begin(&req);
/// renderer.file(&FileResult {
///     path: "x.c".into(),
///     clean: false,
///     source: Some("return 0;\n".into()),
///     formatted: Some("    return 0;\n".into()),
/// });
/// renderer.finish(&Report::default());
/// assert!(renderer.buf.starts_with("<html><body><table>\n"));
/// assert!(renderer.buf.contains("<tr><td>x.c</td><td>false</td></tr>\n"));
/// assert!(renderer.buf.ends_with("</table></body></html>\n"));
/// ```
pub trait Renderer {
    /// Called once before the first file is reported.
    fn begin(&mut self, _req: &Request) {}

    /// The total number of files this run covers — successfully processed
    /// files plus per-file errors (walk-warned unsupported files are
    /// excluded), called by [`crate::run_with_renderer`] right after
    /// [`begin`](Renderer::begin) so renderers that must know whether
    /// per-file headers apply (character mode prints them only when a run
    /// has more than one file) learn the count before the first
    /// [`file`](Renderer::file) event. Default: no-op.
    fn total_files(&mut self, _count: usize) {}

    /// One unsupported regular file found while walking a directory
    /// operand (the style50-parity `unknown file type "<path>",
    /// skipping...` warning). Never called for explicit file arguments;
    /// symlinks, FIFOs, and devices inside the walk are never reported.
    fn skipped(&mut self, _path: &Path) {}

    /// One successfully processed file (clean or dirty).
    fn file(&mut self, _result: &FileResult) {}

    /// One file that could not be processed.
    fn file_error(&mut self, _path: &Path, _message: &str) {}

    /// Called once after all files; final output (e.g. a document) is
    /// emitted here.
    fn finish(&mut self, _report: &Report) {}
}

/// Writes the style50 3.0.0-parity per-file console output and
/// `error: <path>: <message>` lines to stderr. JSON-mode requests are
/// served by [`JsonRenderer`] instead; if a JSON output is requested of
/// this renderer directly, it falls back to the unified diff.
///
/// Character mode reproduces the original's `to_ansi` presentation: a
/// bold-bright-white `Results generated by u50 v<version>` banner (once,
/// u50 branding — a documented divergence), a cyan `::::::::::::::`
/// header per file when the run covers more than one file, green
/// `Looks good!` for clean files (followed by the yellow `But consider
/// adding more comments!` hint when the comment ratio is under 0.10),
/// and the char-diff block (with legend and the yellow `And consider
/// adding more comments!` hint) from [`render_character`] for dirty
/// ones. Split/unified stay plain
/// per-dirty-file diffs (clean files print nothing), matching the
/// original's non-ANSI renderers.
pub struct ConsoleRenderer {
    output: Output,
    color: bool,
    out: Box<dyn Write>,
    banner_emitted: bool,
    total_files: usize,
}

impl Renderer for ConsoleRenderer {
    fn begin(&mut self, _req: &Request) {
        if matches!(self.output, Output::Character) && !self.banner_emitted {
            self.banner_emitted = true;
            let banner = format!("Results generated by u50 v{}", env!("CARGO_PKG_VERSION"));
            let _ = if self.color {
                writeln!(self.out, "{BOLD}{BRIGHT_WHITE}{banner}{RESET}")
            } else {
                writeln!(self.out, "{banner}")
            };
        }
    }

    fn total_files(&mut self, count: usize) {
        self.total_files = count;
    }

    fn skipped(&mut self, path: &Path) {
        eprintln!("unknown file type \"{}\", skipping...", path.display());
    }

    fn file(&mut self, result: &FileResult) {
        if matches!(self.output, Output::Character) {
            // style50 prints the cyan header for every file's block —
            // clean and dirty — but only when a run covers more than one
            // file. Errored files keep their bare stderr line (u50's
            // documented error-channel divergence) and get no header.
            if self.total_files > 1 {
                let name = result.path.display().to_string();
                let _ = if self.color {
                    writeln!(
                        self.out,
                        "{CYAN}{HEADER_RULE}\n{name}\n{HEADER_RULE}{RESET}"
                    )
                } else {
                    writeln!(self.out, "{HEADER_RULE}\n{name}\n{HEADER_RULE}")
                };
            }
            if result.clean {
                let _ = if self.color {
                    writeln!(self.out, "{GREEN}Looks good!{RESET}")
                } else {
                    writeln!(self.out, "Looks good!")
                };
                // style50's `to_ansi` clean path: after `Looks good!`, a
                // yellow `But consider...` line when the comment hint
                // fires (no trailing blank).
                if self.file_hints(result) {
                    let _ = if self.color {
                        writeln!(
                            self.out,
                            "{YELLOW}But consider adding more comments!{RESET}"
                        )
                    } else {
                        writeln!(self.out, "But consider adding more comments!")
                    };
                }
                return;
            }
        } else if result.clean {
            return;
        }
        let (Some(source), Some(formatted)) = (&result.source, &result.formatted) else {
            return;
        };
        let hint = self.file_hints(result);
        let rendered = match self.output {
            Output::Character => render_character(source, formatted, self.color, hint),
            Output::Split => render_split(source, formatted, self.color),
            // `Json`/`Score` never reach this renderer through
            // [`builtin_renderer`]; direct use falls back to the unified
            // diff, like JSON always has.
            Output::Unified | Output::Json | Output::Score => {
                render_unified(source, formatted, &result.path)
            }
        };
        let _ = write!(self.out, "{rendered}");
    }

    fn file_error(&mut self, path: &Path, message: &str) {
        eprintln!("error: {}: {message}", path.display());
    }
}

impl ConsoleRenderer {
    /// Whether style50's comments hint fires for `result`'s normalized
    /// original (character mode only — the original computes the hint in
    /// `to_ansi`): `file["comments"]`, i.e. the comment ratio is strictly
    /// under 0.10. HTML/CSS/SQL are never hinted (no `count_comments`).
    fn file_hints(&self, result: &FileResult) -> bool {
        matches!(self.output, Output::Character)
            && result
                .source
                .as_deref()
                .zip(detect_language(&result.path))
                .is_some_and(|(source, language)| comment_hint(source, language))
    }
}

/// Writes the machine-readable JSON document (one entry per file, with the
/// unified patch for dirty files) in [`finish`](Renderer::finish), plus
/// `error: <path>: <message>` lines to stderr. Per-file events are no-ops:
/// nothing is buffered per file, the document is built from the report at
/// the end.
pub struct JsonRenderer {
    out: Box<dyn Write>,
}

impl Renderer for JsonRenderer {
    fn finish(&mut self, report: &Report) {
        let document = json_document(report);
        let _ = writeln!(
            self.out,
            "{}",
            String::from_utf8_lossy(&json_pretty(&document))
        );
    }

    fn file_error(&mut self, path: &Path, message: &str) {
        eprintln!("error: {}: {message}", path.display());
    }
}

/// Serializes `document` pretty-printed with a **4-space indent**, matching
/// the original style50's JSON formatting (the schema itself stays u50's
/// own — a documented by-design divergence). The bytes carry no trailing
/// newline.
pub(crate) fn json_pretty(document: &serde_json::Value) -> Vec<u8> {
    let mut buf = Vec::new();
    let formatter = serde_json::ser::PrettyFormatter::with_indent(b"    ");
    let mut serializer = serde_json::Serializer::with_formatter(&mut buf, formatter);
    // Serializing a `serde_json::Value` into an in-memory buffer cannot
    // fail, so the result is ignored.
    let _ = Serialize::serialize(document, &mut serializer);
    buf
}

/// Formats an `f64` the way Python's `str()` formats style scores: the
/// shortest decimal string that round-trips, always with a decimal point
/// (`1.0`, not `1`). Rust's `Debug` for `f64` uses the same
/// shortest-round-trip algorithm, so the two agree on every realistic
/// score (a value in `[0, 1]` built from small rational ratios); they
/// differ only for extreme magnitudes where Python switches to
/// exponent notation with a zero-padded exponent (`1e-07`).
#[must_use]
pub(crate) fn py_str_f64(value: f64) -> String {
    format!("{value:?}")
}

/// Writes the style50-compatible aggregate score — a single line such as
/// `0.85` — in [`finish`](Renderer::finish), preceded by one line per
/// file that could not be processed (yellow when `color` is set, matching
/// the original's unconditional termcolor yellow).
///
/// The score mirrors the original style50's score mode exactly: for each
/// successfully processed file, `diffs` accumulates half the number of
/// inserted/deleted lines between the normalized source and its styled
/// content (via the same line diff the display modes use), and `lines`
/// accumulates the styled text's line count — ALL lines for Python (the
/// original's `Python.count_lines` counts blank lines too, per PEP 8),
/// non-blank lines only for every other language. The final score is
/// `max(1 - diffs/lines, 0)`, or `0.0` when no file was checked
/// successfully. Only successful files contribute — the engine never
/// reports [`Renderer::file`] for errored files — matching the original,
/// which sums over successfully checked files only. A styled text with no
/// non-blank lines contributes a `file is empty` error line instead of
/// touching the sums (the original raises a per-file `Error` there). No
/// diff text is produced. Note: u50 keeps its own exit codes in score
/// mode; the original style50 always exits 0.
pub struct ScoreRenderer {
    color: bool,
    out: Box<dyn Write>,
    errors: Vec<String>,
    diffs: f64,
    lines: u64,
}

impl Renderer for ScoreRenderer {
    fn skipped(&mut self, path: &Path) {
        // Buffered so the warning prints before the score line, matching
        // the original's error-then-score ordering.
        self.errors.push(format!(
            "unknown file type \"{}\", skipping...",
            path.display()
        ));
    }

    fn file(&mut self, result: &FileResult) {
        let (Some(source), Some(formatted)) = (&result.source, &result.formatted) else {
            return;
        };
        let change_count = line_diff(source, formatted)
            .iter_all_changes()
            .filter(|change| !matches!(change.tag(), ChangeTag::Equal))
            .count();
        let non_blank = formatted
            .lines()
            .filter(|line| !line.trim().is_empty())
            .count();
        if non_blank == 0 {
            // The original raises `Error("file is empty")` when the styled
            // text has no non-blank lines; the file is then errored (not
            // summed). u50's engine already errors up front for empty
            // input, so this only covers a formatter emptying a file.
            self.errors.push("file is empty".to_owned());
            return;
        }
        // style50's `Python.count_lines` counts ALL lines of the styled
        // text ("blank lines are relevant to style per pep8"); every other
        // language counts non-blank lines only (the shared
        // `style50_count_lines` helper). The empty-text check above stays
        // on the non-blank count for all languages.
        let line_count = detect_language(&result.path).map_or(non_blank, |language| {
            style50_count_lines(formatted, language)
        });
        // Line counts stay far below 2^53, so the conversions are exact.
        #[allow(clippy::cast_precision_loss)]
        let file_diffs = change_count as f64 / 2.0;
        self.diffs += file_diffs;
        self.lines += line_count as u64;
    }

    fn file_error(&mut self, _path: &Path, message: &str) {
        self.errors.push(message.to_owned());
    }

    fn finish(&mut self, _report: &Report) {
        // The original prints each error message bare (no `error: ` prefix
        // — the messages themselves name the file) in file order, colored
        // yellow, then the uncolored score line with a trailing newline.
        for message in &self.errors {
            if self.color {
                let _ = writeln!(self.out, "{YELLOW}{message}{RESET}");
            } else {
                let _ = writeln!(self.out, "{message}");
            }
        }
        let score = if self.lines == 0 {
            0.0
        } else {
            #[allow(clippy::cast_precision_loss)]
            let ratio = self.diffs / self.lines as f64;
            (1.0 - ratio).max(0.0)
        };
        let _ = writeln!(self.out, "{}", py_str_f64(score));
    }
}

/// Returns the built-in renderer for `output`: [`JsonRenderer`] for
/// [`Output::Json`], [`ScoreRenderer`] for [`Output::Score`], and
/// [`ConsoleRenderer`] for the text modes. `out` receives the rendered
/// bytes (stderr output is always written directly).
#[must_use]
pub fn builtin_renderer(output: Output, color: bool, out: Box<dyn Write>) -> Box<dyn Renderer> {
    match output {
        Output::Json => Box::new(JsonRenderer { out }),
        Output::Score => Box::new(ScoreRenderer {
            color,
            out,
            errors: Vec::new(),
            diffs: 0.0,
            lines: 0,
        }),
        Output::Character | Output::Split | Output::Unified => Box::new(ConsoleRenderer {
            output,
            color,
            out,
            banner_emitted: false,
            total_files: 0,
        }),
    }
}
