[package]
name = "u50_style"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
dirs = { workspace = true }
fs-err = { workspace = true }
fslock = { workspace = true }
indicatif = { workspace = true }
leptos = { workspace = true, features = ["ssr"] }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
similar = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
u50_tools = { path = "../u50_tools" }
unicode-width = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
which = { workspace = true }
