[package]
name = "u50_cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "u50"
path = "src/main.rs"

[dependencies]
u50_check = { path = "../u50_check" }
u50_style = { path = "../u50_style" }
u50_submit = { path = "../u50_submit" }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
