//! The ANSI renderer: check50's `to_ansi` (plain when stdout is not a
//! terminal — the piped ground truth — and termcolor-style colors when
//! it is): a bold-white banner line, then `:)`/`:|`/`:(` lines with the
//! cause rationale, help, and error details, plus the optional log.
//!
//! Student-controlled text (descriptions, rationales, output payloads,
//! log lines) is sanitized before rendering: control characters — most
//! importantly the ANSI escape byte — cannot smuggle terminal escape
//! sequences into u50's own output.

use std::fmt::Write as _;

use crossterm::Command as _;
use crossterm::style::{Attribute, Color, SetAttribute, SetForegroundColor};

use super::RenderInput;

/// The colored-line closure shared by the render arms.
type ColoredFn<'a> = dyn Fn(&mut String, Color, &[(bool, Attribute)], &str) + 'a;
use crate::result::{Cause, CheckResult};

/// Escapes control characters in student-controlled text so rendered
/// output cannot smuggle terminal escape sequences (ANSI injection).
/// Newlines and tabs pass through (the renderer's own line structure).
fn sanitize(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '\n' | '\t' => out.push(ch),
            c if c.is_control() => {
                let _ = write!(out, "\\u{{{:04x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

/// Renders the ANSI output. Colors are emitted only when `input.color`
/// is set (stdout is a terminal); the plain form matches check50's piped
/// output byte for byte (modulo the documented u50 branding).
#[must_use]
pub(crate) fn render_ansi(input: &RenderInput) -> String {
    let mut out = String::new();
    let colored = |out: &mut String, color: Color, attrs: &[(bool, Attribute)], text: &str| {
        // One choke point for student-controlled text.
        let text = &sanitize(text);
        if !input.color {
            out.push_str(text);
            return;
        }
        for &(set, attribute) in attrs {
            if set {
                let _ = SetAttribute(attribute).write_ansi(out);
            }
        }
        let _ = SetForegroundColor(color).write_ansi(out);
        out.push_str(text);
        let _ = SetAttribute(Attribute::Reset).write_ansi(out);
    };

    colored(
        &mut out,
        Color::White,
        &[(true, Attribute::Bold)],
        &format!(
            "Results for {} generated by u50 v{}",
            input.slug, input.version
        ),
    );

    if let Some(error) = input.error {
        out.push('\n');
        colored(&mut out, Color::Red, &[], &error.actions.message);
        if error.actions.show_traceback {
            for line in &error.traceback {
                out.push_str(line);
            }
        }
        return out;
    }

    for result in input.results {
        out.push('\n');
        render_result(&mut out, input, result, &colored);
    }
    out
}

fn render_result(out: &mut String, input: &RenderInput, result: &CheckResult, colored: &ColoredFn) {
    match result.passed {
        Some(true) => colored(
            out,
            Color::Green,
            &[],
            &format!(":) {}", result.description),
        ),
        Some(false) => {
            colored(out, Color::Red, &[], &format!(":( {}", result.description));
            if let Some(cause) = &result.cause {
                match cause {
                    Cause::Failure { rationale, help } => {
                        colored(out, Color::Red, &[], &format!("    {rationale}"));
                        if let Some(help) = help {
                            colored(out, Color::Red, &[], &format!("    {help}"));
                        }
                    }
                    Cause::Mismatch {
                        rationale,
                        help,
                        expected,
                        actual,
                    } => {
                        colored(out, Color::Red, &[], &format!("    {rationale}"));
                        if let Some(help) = help {
                            colored(out, Color::Red, &[], &format!("    {help}"));
                        }
                        write!(out, "    expected: {expected}")
                            .expect("writing to a String cannot fail");
                        write!(out, "    actual: {actual}")
                            .expect("writing to a String cannot fail");
                    }
                    Cause::Skipped { rationale } => {
                        colored(out, Color::Red, &[], &format!("    {rationale}"));
                    }
                    Cause::Error { rationale, error } => {
                        colored(out, Color::Red, &[], &format!("    {rationale}"));
                        write!(out, "    {}: {}", error.kind, error.value)
                            .expect("writing to a String cannot fail");
                        for line in &error.traceback {
                            write!(out, "    {line}").expect("writing to a String cannot fail");
                        }
                    }
                }
            }
        }
        None => {
            colored(
                out,
                Color::Yellow,
                &[],
                &format!(":| {}", result.description),
            );
            if let Some(cause) = &result.cause {
                match cause {
                    Cause::Failure { rationale, help } => {
                        colored(out, Color::Yellow, &[], &format!("    {rationale}"));
                        if let Some(help) = help {
                            colored(out, Color::Yellow, &[], &format!("    {help}"));
                        }
                    }
                    Cause::Mismatch {
                        rationale,
                        help,
                        expected,
                        actual,
                    } => {
                        colored(out, Color::Yellow, &[], &format!("    {rationale}"));
                        if let Some(help) = help {
                            colored(out, Color::Yellow, &[], &format!("    {help}"));
                        }
                        write!(out, "    expected: {expected}")
                            .expect("writing to a String cannot fail");
                        write!(out, "    actual: {actual}")
                            .expect("writing to a String cannot fail");
                    }
                    Cause::Skipped { rationale } => {
                        colored(out, Color::Yellow, &[], &format!("    {rationale}"));
                    }
                    Cause::Error { rationale, error } => {
                        colored(out, Color::Yellow, &[], &format!("    {rationale}"));
                        write!(out, "    {}: {}", error.kind, error.value)
                            .expect("writing to a String cannot fail");
                        for line in &error.traceback {
                            write!(out, "    {line}").expect("writing to a String cannot fail");
                        }
                    }
                }
            }
        }
    }
    if input.show_log {
        for line in &result.log {
            write!(out, "    {line}").expect("writing to a String cannot fail");
        }
    }
}
